{
  "hash": "b1a0f5abfcd77420a4c1e05ae3d98dd2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Rita Wu\"\ndate: today\n\nparams:\n  state: \"FL\"\n\nformat:\n  html:\n    toc: true\n    code-fold: false\n\nexecute:\n  warning: false\n  message: false\n---\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\n\n**In this analysis, I look at Occupied housing unit numbers across counties in Florida, and\nask which communities we measure most and least reliably.**\n\n\n```r\nvars <- load_variables(2023, \"acs5\")\nView(vars)\n```\n\nThen use the search box.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- params$state      # two-letter abbreviation, in quotes\nmy_variable <- \"B25002_002\"     # the variable code, in quotes B25002_002 Occupied Housing Units\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                     variable   estimate   moe\n  <chr> <chr>                    <chr>         <dbl> <dbl>\n1 12001 Alachua County, Florida  B25002_002   112776  1105\n2 12003 Baker County, Florida    B25002_002     9012   295\n3 12005 Bay County, Florida      B25002_002    76118  1106\n4 12007 Bradford County, Florida B25002_002     9104   367\n5 12009 Brevard County, Florida  B25002_002   251889  1622\n6 12011 Broward County, Florida  B25002_002   749372  2712\n```\n\n\n:::\n:::\n\n\n**[How many rows did you get? Does that match the number of counties in your state?]**\nthere are 67 rows I got, it matches with the number of counties in Florida.\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                      estimate   moe moe_pct\n   <chr>                        <dbl> <dbl>   <dbl>\n 1 Lafayette County, Florida     2619   231    8.82\n 2 Liberty County, Florida       2554   177    6.93\n 3 Dixie County, Florida         6130   386    6.30\n 4 Glades County, Florida        4560   263    5.77\n 5 Gulf County, Florida          5800   334    5.76\n 6 Calhoun County, Florida       4625   225    4.86\n 7 Hamilton County, Florida      4360   202    4.63\n 8 Taylor County, Florida        7571   329    4.35\n 9 Franklin County, Florida      4918   200    4.07\n10 Bradford County, Florida      9104   367    4.03\n```\n\n\n:::\n:::\n\n\n\n\n**[Which county has the largest margin of error relative to its estimate? How large\nis it?]**\n\nthe least reliable county is Lafayette County in Florida, with a MOE_pct of 8.82, followed by Liberty County, with a MOE_pct of 6.93.\n\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 2.5  ~ \"High confidence\",\n    moe_pct < 5 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    43\n2 Low confidence      5\n3 Moderate           19\n```\n\n\n:::\n:::\n\n\n\n\n**[How many counties fall into each category?]**\nI use the threshold of 2.5% as high confidence, 5% as moderate, and above that as low confidence.\nOf the whole 67 counties, 43 of them are high confidence, 19 are moderate, and 5 are low confidence.\n\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                     myvarE myvarM    popE  popM\n  <chr> <chr>                     <dbl>  <dbl>   <dbl> <dbl>\n1 12001 Alachua County, Florida  112776   1105  281751    NA\n2 12003 Baker County, Florida      9012    295   28186    NA\n3 12005 Bay County, Florida       76118   1106  181368    NA\n4 12007 Bradford County, Florida   9104    367   27888    NA\n5 12009 Brevard County, Florida  251889   1622  620533    NA\n6 12011 Broward County, Florida  749372   2712 1946127    NA\n```\n\n\n:::\n:::\n\n\n\nNotice the column names: `myvarE`, `myvarM`, `popE`, `popM`. The `E` and `M`\nsuffixes are estimate and margin of error.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 15 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         62        352728.\n2 Moderate                 5         11947.\n```\n\n\n:::\n:::\n\n\n\n**[What is the average population of high-confidence counties versus low-confidence\ncounties? Is there a pattern?]**\n\nThe average population of high-confidence counties is 352,728. The average population for low-confidence counties is 11,947. As a result, we can see that counties with fewer population will likely to end up in higher margin of error. \n\n---\n\n## What this means for policy\n\n\nAddress all three:\n\n1. **Which communities in your state do we know the least about?** \nThe ACS data suggest that we know the least about smaller communities in Florida, particularly Lafayette County and Liberty County. Lafayette County has the largest relative margin of error in my analysis, with a MOE of 8.82%, followed by Liberty County at 6.93%. In comparison, 43 of Florida’s 67 counties fall into my high-confidence category, while 19 are moderate and only 5 are classified as low confidence.\n\n2. **Why?** \nThis pattern is related to how the ACS is collected. Unlike a complete census, the ACS estimates population and housing characteristics from a sample of households. Smaller counties generally have fewer households and therefore fewer sampled households. With a smaller sample size, estimates are subject to greater sampling uncertainty, which can produce a larger margin of error relative to the estimate. My results illustrate this relationship: high-confidence counties have an average population of 352,728, while low-confidence counties have an average population of only 11,947.\n   \n3. **What could go wrong?** \nThis uncertainty matters for public policy because agencies may treat all county-level estimates as equally precise. If funding were allocated based on occupied housing unit estimates without considering their uncertainty, smaller counties could be disadvantaged. Their estimates are less reliable, so policymakers might underestimate or overestimate their actual housing needs and allocate resources based on numbers that appear more certain than they really are.\n\n---\n\n\n\n1. **Propagate the margin of error.** If you compute a derived value — a percentage,\n   a ratio, a sum — its uncertainty depends on the uncertainty of its inputs, and\n   you can't just carry the original MOE along. The Census Bureau publishes formulas\n   for this, and `tidycensus` implements them: `moe_sum()`, `moe_prop()`,\n   `moe_ratio()`. Compute something derived, and get its margin of error right.\n\n2. **Parameterize the report.** Add `params:` to the YAML so the state is an input\n   rather than hard-coded, and the same file regenerates for any state. Render it\n   from the terminal with `quarto render assignment2.qmd -P state:NY`.\n\n3. **Write a function and iterate.** Wrap the data pull in a function, then use\n   `purrr::map_dfr()` to run it across several states at once. Does the\n   small-places-are-noisier pattern hold everywhere, or are some states different?\n\n4. **Change the geographic scale.** Run the same variable at `geography = \"tract\"`\n   inside one county. Compare the margins of error to what you saw at county level.\n   What does that imply about the resolution at which you can actually trust ACS\n   data?\n\nIf you try one, add a short section describing what you did and what you found.\n\n2. Done in the heading.\n\n3, the small-places-are-noisier pattern holds for FL, NY, TX, OH, PA.\n\n::: {.cell}\n\n```{.r .cell-code}\nget_county_data <- function(state_abbr) {\n  \n  get_acs(\n    geography = \"county\",\n    variables = c(\n      occupied = \"B25002_002\",\n      population = \"B01003_001\"\n    ),\n    state = state_abbr,\n    year = 2023,\n    survey = \"acs5\",\n    output = \"wide\"\n  ) %>%\n    mutate(\n      state = state_abbr,\n      estimate = occupiedE,\n      moe = occupiedM,\n      population = populationE,\n      moe_pct = moe / estimate * 100,\n      reliability = case_when(\n        moe_pct < 2.5 ~ \"High confidence\",\n        moe_pct < 5 ~ \"Moderate\",\n        TRUE ~ \"Low confidence\"\n      )\n    ) %>%\n    select(\n      GEOID, NAME, state,\n      estimate, moe, population,\n      moe_pct, reliability\n    )\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstates <- c(\"FL\", \"NY\", \"TX\", \"OH\", \"PA\")\n\nall_states <- purrr::map_dfr(\n  states,\n  get_county_data\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_result <- all_states %>%\n  group_by(state, reliability) %>%\n  summarize(\n    avg_moe_pct = mean(moe_pct),\n    median_moe_pct = median(moe_pct),\n    max_moe_pct = max(moe_pct),\n    occupied_housing = mean(estimate),\n    pop = mean(population)\n  ) %>%\n  arrange(desc(avg_moe_pct))\n\nstate_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 14 × 7\n# Groups:   state [5]\n   state reliability     avg_moe_pct median_moe_pct max_moe_pct occupied_housing\n   <chr> <chr>                 <dbl>          <dbl>       <dbl>            <dbl>\n 1 TX    Low confidence        12.0           7.77        82.4             1944.\n 2 NY    Low confidence         7.01          7.01         7.01            2111 \n 3 FL    Low confidence         6.71          6.30         8.82            4333.\n 4 PA    Low confidence         5.45          5.45         5.45            1944 \n 5 TX    Moderate               3.64          3.59         4.98            8192.\n 6 PA    Moderate               3.59          4.13         4.14            9591.\n 7 FL    Moderate               3.48          3.27         4.86           10004.\n 8 OH    Moderate               3.14          3.18         4.07            9068.\n 9 NY    Moderate               3.09          2.84         4.16           15688.\n10 TX    High confidence        1.42          1.35         2.46          126750.\n11 OH    High confidence        1.34          1.35         2.47           62823.\n12 PA    High confidence        1.24          1.20         2.40           82613.\n13 NY    High confidence        1.23          1.28         2.39          133405.\n14 FL    High confidence        1.08          0.980        2.28          193934.\n# ℹ 1 more variable: pop <dbl>\n```\n\n\n:::\n:::\n\n\n",
    "supporting": [
      "assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}